import logging
import json
import google.generativeai as genai
from core.config import get_settings

logger = logging.getLogger(__name__)

_MODEL_NAME = "gemini-3-flash-preview"

def _configure_genai() -> None:
    settings = get_settings()
    genai.configure(api_key=settings.GEMINI_API_KEY)

async def generate_structured_content(transcript_text: str, content_type: str) -> str:
    """
    Generate structured study material from the given transcript text.
    Returns JSON strings for interactive components, and Markdown for notes.
    """
    _configure_genai()
    
    if content_type == "notes":
        model = genai.GenerativeModel(model_name=_MODEL_NAME)
        prompt = (
            "You are an expert tutor. Create comprehensive, beautifully formatted Markdown study notes "
            "from the following transcript. Use headings, bullet points, bold text for key terms, "
            "and blockquotes for important concepts.\n\n"
            f"TRANSCRIPT:\n{transcript_text}"
        )
        response = await model.generate_content_async(prompt)
        return json.dumps({"content": response.text})

    # For Quiz, Flashcards, and Mock Test, we enforce JSON output
    model = genai.GenerativeModel(
        model_name=_MODEL_NAME,
        generation_config=genai.GenerationConfig(
            response_mime_type="application/json",
        )
    )

    if content_type == "flashcards":
        prompt = (
            "You are an expert tutor. Create exactly 10 highly effective flashcards based on the following transcript. "
            "Identify the most important terms, concepts, or historical facts. "
            "The output MUST be a JSON array of objects, where each object has exactly two keys: 'front' and 'back'.\n\n"
            "Example format:\n"
            "[\n  {\"front\": \"Term 1\", \"back\": \"Definition 1\"},\n  {\"front\": \"Concept 2\", \"back\": \"Explanation 2\"}\n]\n\n"
            f"TRANSCRIPT:\n{transcript_text}"
        )
        
    elif content_type == "quiz":
        prompt = (
            "You are an expert tutor. Create a multiple-choice quiz with exactly 5 questions based on the following transcript. "
            "The output MUST be a JSON array of objects. Each object MUST have: "
            "'question' (string), 'options' (array of exactly 4 strings), 'correct_answer' (string matching one option), and 'explanation' (string).\n\n"
            "Example format:\n"
            "[\n  {\n    \"question\": \"What is X?\",\n    \"options\": [\"A\", \"B\", \"C\", \"D\"],\n    \"correct_answer\": \"B\",\n    \"explanation\": \"Because...\"\n  }\n]\n\n"
            f"TRANSCRIPT:\n{transcript_text}"
        )
        
    elif content_type == "mock_test":
        prompt = (
            "You are an expert tutor. Create a comprehensive Mock Test based on the following transcript. "
            "The output MUST be a JSON object with two arrays: 'multiple_choice' (5 questions) and 'true_false' (5 questions).\n\n"
            "For 'multiple_choice', use the same format as a standard quiz (question, options, correct_answer, explanation).\n"
            "For 'true_false', each object MUST have: 'statement' (string), 'is_true' (boolean), and 'explanation' (string).\n\n"
            f"TRANSCRIPT:\n{transcript_text}"
        )
    else:
        raise ValueError(f"Unknown content_type: {content_type}")

    logger.info(f"Generating {content_type}...")
    response = await model.generate_content_async(prompt)
    
    # Return the raw JSON string generated by the model
    return response.text
